### ISSUE TITLE
AWS Bottlerocket support

### ISSUE THREAD

**Issue by psact** [IBM/core-dump-handler#103]
When deploying the helm chart on bottlerocket nodes, it doesn't appear the containerd socket is available under /run.  I made a modification to the helm chart locally to mount it, and everything seemed to work.  I can make a PR with my changes wrapped in a conditional, but I'm not sure if there are other use cases for customizing where the socket exists based on the OS.

https://github.com/psact/core-dump-handler/commit/10b6c33571252286a8eab87955b61a121cc4a468

**Comment by No9** [comment]
Hey @psact Thanks for the letting us know about this variant. 
It's important for the project that we capture these scenarios.

Looks like an additional values override would cover this? 
Something called `values.aws.bottlerocket.yaml` stored in https://github.com/IBM/core-dump-handler/tree/main/charts/core-dump-handler and containing the variables you set.

Also update the table in the chart README and we are good to go.
https://github.com/IBM/core-dump-handler/blob/main/charts/core-dump-handler/README.md#installing-the-chart

**Comment by psact** [comment]
I had set `crioEndpoint: "unix:///run/dockershim.sock"`, and ` deployCrioConfig: true` which seemed to work. I kept the default dump mount location at ` /var/mnt/core-dump-handler`

I went ahead and added some parameters for mounting the host docker socket, and pushed to my branch.

https://github.com/psact/core-dump-handler/tree/bottlerocket-dockersock

I can open a PR if you would like.

**Comment by No9** [comment]
Ah now I understand - Thanks for clarifying and putting together the yaml file.
Happy to take this as a PR

**Comment by No9** [comment]
Fixed in [V8.6.1](https://github.com/IBM/core-dump-handler/releases/tag/v8.6.1)
Thanks again for the PR
