### ISSUE TITLE
Document installation on different cloud providers

### ISSUE THREAD

**Issue by No9** [IBM/core-dump-handler#12]
It would be great if there were markdown files for each of the working cloud providers that contained documentation for setting the project up on the different k8s services and object storage environments. This may be as simple as finding the different links to the documentation for setting up a cluster, configuring the kubectl client and configuring object storage.

**Comment by adinhtdsibm** [comment]
@No9 As discussed, I can work on this issue. Please do assign my name and I will update you once I am done with the documentation.

**Comment by No9** [comment]
Closing as all the configuration for the different cloud providers has been captured as separate value.yaml files in the chart base folder and documented in the chart [README.md](https://github.com/IBM/core-dump-handler/blob/main/charts/core-dump-handler/README.md)
