### ISSUE TITLE
pullSecrets is not used inside daemonset.yaml

### ISSUE THREAD

**Issue by rohsaini** [IBM/core-dump-handler#129]
In charts, pullSecrets is present in values.yaml but is not being used inside templates/daemonset.yaml.

**Comment by No9** [comment]
Hi @rohsaini 
Happy to take a pull request for this if you require it.

**Comment by rohsaini** [comment]
Hi @No9 
Thanks. Yes, this is required by me.

**Comment by No9** [comment]
Hi @rohsaini 
Would you mind opening a PR with that and I can pull it in as we have a gated review process.
Also please remember to sign the commit for the DCO 
Thanks

**Comment by rohsaini** [comment]
Sure. Raised https://github.com/IBM/core-dump-handler/pull/130

Thanks.

**Comment by No9** [comment]
Thanks again for the PR - I'll release in the next few days.

**Comment by rohsaini** [comment]
Thanks @No9
