### ISSUE TITLE
Deployment error fails to EKS

### ISSUE THREAD

**Issue by dcieslak19973** [IBM/core-dump-handler#143]
Seeing the following in the logs:

```
Bucket Creation Failed: serde_xml: custom: missing field `AssumeRoleWithWebIdentityResult`
```

Not sure how to resolve.  Deployed using the `values.aws.sts.yaml` with an ARN specific to our AWS account

**Comment by No9** [comment]
Hi @dcieslak19973 
Pulling in @razielgn as they PRd the sts file to see if there are any ideas

**Comment by No9** [comment]
Related? https://github.com/IBM/core-dump-handler/issues/140

**Comment by usimd** [comment]
Yeah, can confirm this works after adding the service account token secret.
