### ISSUE TITLE
Core dump files housekeeping

### ISSUE THREAD

**Issue by laurentiusoica** [IBM/core-dump-handler#145]
Hi All,

When handling core dumps with core-dump-handler, what is the recommended mechanism to cleanup collected core files from worker nodes?

**Comment by No9** [comment]
Hey @laurentiusoica 
The core file is piped directly into the zip file
https://github.com/IBM/core-dump-handler/blob/main/core-dump-composer/src/main.rs#L171

and the zip is removed by the agent after a successful upload to the Object Store 
https://github.com/IBM/core-dump-handler/blob/main/core-dump-agent/src/main.rs#L341 

There should be no need to "clean up" on the server.

**Comment by laurentiusoica** [comment]
Thanks!
