### ISSUE TITLE
Add support for Azure Storage Account blobs [feature request] 

### ISSUE THREAD

**Issue by sshipway** [IBM/core-dump-handler#164]
**Summary**
It would be very helpful if this also supported saving core dump files to an Azure Storage Account, as well as to an S3 store.  Ideally, this should allow Service Principal authentication, rather than Access Key or SAS (which have management and security issues).

**Use Case**
Containers running in an AKS Kubernetes cluster should be able to write direct to a blob container

**Alternatives**
There are some S3-to-SA proxies available, but they require an additional container and can have translation problems, particularly with Metadata conversion.

**Comment by No9** [comment]
Thanks for the interest in the project 
As per https://github.com/IBM/core-dump-handler/issues/74 there is no active development planned for Azure Blob Storage but PRs are welcome.
