### ISSUE TITLE
v9.0.0 image built for arm64 runners

### ISSUE THREAD

**Issue by sheklesworth** [IBM/core-dump-handler#168]
I tried deploying the v9.0.0 image, replacing our existing v8.10.0 image, but kept getting `exec /app/core-dump-agent: exec format error` errors on deployment.

Looking a bit closer, past versions were built for amd64 runners:
```bash
$  docker image inspect quay.io/icdh/core-dump-handler:v8.10.0 | jq '.[].Architecture'
"amd64"
```
But the v9.0.0 version was built for arm64 runners:
```bash
$  docker image inspect quay.io/icdh/core-dump-handler:v9.0.0 | jq '.[].Architecture'
"arm64"
```
Would it be possible to get an official amd64 version of the  latest package?

**Comment by No9** [comment]
Thanks for the report.
There was an issue with the quay.io build server during release so we had to use an internal runner and despite it being an `amd64` machine it defaulted to `arm64`. 
This should be resolved now. 
```
podman image inspect quay.io/icdh/core-dump-handler:v9.0.0 | jq '.[].Architecture'
"amd64"
```
