### ISSUE TITLE
Optionally seperate S3 object directory by metadata

### ISSUE THREAD

**Issue by isbee** [IBM/core-dump-handler#28]
As far as I know, dump file name is `{CORE_UUID}-dump-{CORE_TIMESTAMP}-{CORE_HOSTNAME}-{CORE_EXE_NAME}-{CORE_PID}-{CORE_SIGNAL}` and this is equal to S3 object name.

When someone uses a single S3 bucket, and If core-dump-handler is used on multi-cloud/multi-cluster/multi-region, it's hard to figure out where does a dump file come from. Since these metadatas are statically settled on deploying daemonset, It can be injected via environment variable and used for S3 upload directory seperation.

But maybe seperating S3 bucket is just enough, So it'll be great we can choose
1. Multiple S3 bucket + flat S3 directory(by vendor/cluster-name)
2. Single S3 bucket + nested S3 directory

Additionally, it would be nice to be able to distinguish the namespace of crashed containers. From core-dump-handler's point of view, crashed-container's namespace are runtime metadata so it'll be hard to figure out. I guess modifying core_pattern to `|{HOST_LOCATION}/{CORE_DUMP_COMPOSER_NAME} -c=%c -e=%e -p=%p -s=%s -t=%t -d={HOST_DIR}/core -h=%h -E=%E -NS=$NAMESPACE` might work since `%h` is crashed-container's hostname, not core-dump-handler agent's hostname.

**Comment by No9** [comment]
As there are no further comments I am going to close this but feel free to reopen if you have some more detail on the paths requirements
