### ISSUE TITLE
Watch filesystem rather than polling

### ISSUE THREAD

**Issue by isbee** [IBM/core-dump-handler#29]
Agent take polling approach to check whether core dumps are exist. Theoretically dumps are rarely generated so in most cases, it becomes a useless operation.

Therefore, I think it is better to optimize using filesystem watch instead of polling. Most OSs support this feature(e.g. Linux's inotify, BSD's kqueue, ...) and there is some rust open source related to this.

There are two things to consider when using watch
1. Linux's inotify, BSD's kqueue are lack of recursive watch feature. So if we want to watch recursive directories, application-level recursive watch is needed and we should release that watch before delete it.
    - But currently we don't need recursive watch, so it's not problem.
2. There might be some missing events(due to agent crash or something), so agent should scan target directory and upload existing dumps once on init.

**Comment by No9** [comment]
Hey @isbee there is an initial implementation of iNotify here 
https://github.com/IBM/core-dump-handler/tree/schedule-watch
You should be able to checkout that branch and run it with your usual settings but note the scheduled approach and Inotify are mutually exclusive.
As you suggested the service sweeps the folder on startup 
https://github.com/IBM/core-dump-handler/blob/schedule-watch/core-dump-agent/src/main.rs#L121 
Let us know how you get on with it and if you have any comments.

**Comment by No9** [comment]
Merging as part of PR https://github.com/IBM/core-dump-handler/pull/43
