### ISSUE TITLE
Release to chart repo

### ISSUE THREAD

**Issue by timbuchwaldt** [IBM/core-dump-handler#33]
It's a best practice to upload the released helm chart to a helm repo, this allows users like us to define a dependency on it and e.g. automatically update it.

**Comment by No9** [comment]
Completed in https://github.com/IBM/core-dump-handler/releases/tag/v5.0.0 with package and verification now part of the releases.
index.yaml now available at https://ibm.github.io/core-dump-handler/index.yaml
