### ISSUE TITLE
Beautify Chart Repo Page

### ISSUE THREAD

**Issue by No9** [IBM/core-dump-handler#34]
Currently the index.html page is fairly basic 
https://ibm.github.io/core-dump-handler/
it would be nice to have a prettier page that displayed the contents of index.yaml

**Comment by sunidhisachan** [comment]
Hey @No9 I can try this

**Comment by No9** [comment]
Great - @sunidhisachan 
I would be good if we don't have to rely on any build-steps if possible. 
I will assign it to you.

**Comment by No9** [comment]
@sunidhisachan should have said 
if you have any questions please feel free to ask. Doesn't matter how small it is.

**Comment by No9** [comment]
Would also be good if we can either incorporate this widget 
https://artifacthub.io/packages/helm/core-dump-handler/core-dump-handler?modal=widget 
Or even expand on it?
```
<div class="artifacthub-widget" data-url="https://artifacthub.io/packages/helm/core-dump-handler/core-dump-handler" data-theme="light" data-header="true" data-stars="true" data-responsive="false"><blockquote><p lang="en" dir="ltr"><b>core-dump-handler</b>: A Helm chart for deploying a core dump management system to Kubernetes</p>&mdash; Open in <a href="https://artifacthub.io/packages/helm/core-dump-handler/core-dump-handler">Artifact Hub</a></blockquote></div><script async src="https://artifacthub.io/artifacthub-widget.js"></script> 
```

**Comment by No9** [comment]
OK put an initial piece in place so I am going to close this.
https://github.com/IBM/core-dump-handler/commit/d06ed30df09c32e14df43bf42966d6a1805d1a6f 
Happy to take another PR If there are any further improvements
