### ISSUE TITLE
Alternative upload sink

### ISSUE THREAD

**Issue by tjungblu** [IBM/core-dump-handler#48]
(yet another follow-up to the conversations that triggered #44 + #47)

Our customer is in the Telco space and already has a so called "Element Management System" that allows to observe crashes and manage crash dumps. They would like to upload the dump there instead of an ObjectStore.

I don't really have a good understanding of what they can upload and how that works in detail yet, I just wanted to figure out if we can make the upload system more composable. 

One solution that immediately came to me would be to have a configurable sidecar container in the DS (basically just config in helm and values.yaml) that can run inotify or poll on the coreDirectory and upload to where it should go.

**Comment by No9** [comment]
Yes. Today you should be able disable the default agent upload by setting the scheduler to be none and disabling the iNotify.
Something like this should work but would need to be tested.
```
schedule: "* * * * * *"
useINotify: false
```
You can then deploy your own uploader either as part of the chart or out of band.
If we are to support different uploaders more systematically we should probably look to move the deployment of the service into an init container and also consider how these can be configured within an operator.
Tagging https://github.com/IBM/core-dump-operator/issues/1

**Comment by No9** [comment]
Commented in the new FAQ https://github.com/IBM/core-dump-handler/commit/58ef93d43e59c83600bac40276a92c6bf1b164ee
Specifically https://github.com/IBM/core-dump-handler/blob/pod-logs/FAQ.md#how-should-i-integrate-my-own-uploader
