### ISSUE TITLE
8.0.0 fails to take crashdump

### ISSUE THREAD

**Issue by splitice** [IBM/core-dump-handler#66]
Did an upgrade to 8.0.0

Started getting the following in dmesg (and no dump handled)

```
[1073776.504905] Core dump to |/var/mnt/core-dump-handler/cdc pipe failed
```

Any ideas?

**Comment by No9** [comment]
Strange - There was no work done on cdc as part of 8.0.0, it's still on 7.1.0 
Can you look at the composer log?

If you took the default install location you can exec into the agent pod and run 
`cat /var/mnt/core-dump-handler/composer.log`
If there is nothing in there reinstall with `--set composer.logLevel="Debug"` and recheck the log.

Also there was a patch release so please use 8.0.1

BTW integration tests are ran as part of the release validation and this error didn't come up.

**Comment by splitice** [comment]
Thank you for that information - I'm testing something and will get back to you when I have results. It might have been an error during manifest update.

**Comment by splitice** [comment]
By the way when doing a `kubectl apply` to deploy a modified daemonset the first pod got stuck in terminating.

```
Events:
  Type     Reason             Age   From     Message
  ----     ------             ----  ----     -------
  Normal   Killing            111s  kubelet  Stopping container coredump-container
  Warning  FailedPreStopHook  110s  kubelet  Exec lifecycle hook ([/app/core-dump-agent remove]) for Container "coredump-container" in Pod "core-dump-handler-czbsm_default(23ffd715-a00e-4bc2-be70-87f36df7fbe2)" failed - error: command '/app/core-dump-agent remove' exited with 1: [2022-02-09T08:10:19Z INFO  core_dump_agent] no .env file found
     That's ok if running in kubernetes
[2022-02-09T08:10:19Z INFO  core_dump_agent] Removing /var/mnt/core-dump-handler
[2022-02-09T08:10:19Z INFO  core_dump_agent] Restoring Backup of core_pattern
[2022-02-09T08:10:20Z INFO  core_dump_agent] Restoring Backup of core_pipe_limit
[2022-02-09T08:10:20Z INFO  core_dump_agent] Restoring Backup of suid_dumpable
Error: No such file or directory (os error 2)
, message: "kernel.core_pattern = core\nkernel.core_pipe_limit = 0\nfs.suid_dumpable = 0\n[2022-02-09T08:10:19Z INFO  core_dump_agent] no .env file found \n     That's ok if running in kubernetes\n[2022-02-09T08:10:19Z INFO  core_dump_agent] Removing /var/mnt/core-dump-handler\n[2022-02-09T08:10:19Z INFO  core_dump_agent] Restoring Backup of core_pattern\n[2022-02-09T08:10:20Z INFO  core_dump_agent] Restoring Backup of core_pipe_limit\n[2022-02-09T08:10:20Z INFO  core_dump_agent] Restoring Backup of suid_dumpable\nError: No such file or directory (os error 2)\n"
```

**Comment by No9** [comment]
Hey @splitice Did you get this resolved?
If so can we close this or is there follow on required?
Thanks

**Comment by splitice** [comment]
It looks resolved after a restart of the daemonset on the new version. Haven't had a crash to test it since.
