### ISSUE TITLE
enhancement: ability to set fs.suid_dumpable

### ISSUE THREAD

**Issue by andytson** [IBM/core-dump-handler#7]
Lots of applications start as root user, and setuid in order to run with lower privileges. This is usually to do with opening log files or binding to privileged ports.

Segfaults from these setuid'd processes do not create core dumps by default, and require the sysctl config `fs.suid_dumpable` set to 1 or 2.

Would it be possible to have an env var for the core-dump-agent to set this sysctl setting? 2 should be best, as it prevents the process being able to read it (if the host volume was even mounted in the container).

Processes that do this include:

* nginx
* apache
* php-fpm

**Comment by andytson** [comment]
The following triggers a segfault after setuid. It's not otherwise as simple as `su -c 'kill -11 $$' app` as the segfault has to be in the setuid process rather than child process

https://gist.github.com/andytson-inviqa/e1c933ccaa1825a9c4449cbf823c3c13

**Comment by No9** [comment]
Quick update I have an implementation of this here https://github.com/IBM/core-dump-handler/tree/suid-support 
My quay.io access is broken due to the move to SSO so I need to setup another account to host the images and test. 
Should get that done soon and I'll merge after that.

**Comment by No9** [comment]
Actually setting up the new quay repo was easier than I thought 
https://quay.io/repository/icdh/core-dump-handler?tab=builds 

I have to wrap up for the day but you can point the chart to  
`quay.io/icdh/core-dump-handler:suid-support` to test

**Comment by No9** [comment]
Tested the suid-support branch with the command `kubectl run -i -t segfaulter --image=quay.io/icdh/segfaulter --restart=Never`
Where quay.io/icdh/segfaulter is based on the code initially supplied. -> https://github.com/No9/segfaulter 

There was a nit in the quote escaping in the chart but now seems to work as expected and core-dumps are generated as expected.
I'll let this sit for a few days and if there's no further feedback I'll merge

**Comment by andytson** [comment]
I've tested it myself and it appears to work as expected.

One comment though, but should SUID_LIMIT instead be called SUID_DUMPABLE?

As for quotes, I tend to do `value: {{ .VAR | quote }}` as that ensures proper escaping

**Comment by andytson** [comment]
also thanks for the logs location fix, I was wondering why it was in /node without a container mount to view it

**Comment by No9** [comment]
Appreciate the feedback - changed to SUID_DUMPABLE and used quotes - thanks for the tip.
If there's nothing else I'll validate the file lock code I've also put in and then do a release.

**Comment by No9** [comment]
lock code seems to be working well - Ran with 5ms intervals and the file uploads uncorrupted.

**Comment by No9** [comment]
Merged https://github.com/IBM/core-dump-handler/pull/11 and built release [v2.1.0](https://github.com/IBM/core-dump-handler/releases/tag/v2.1.0)
Thanks again @andytson for opening this issue and providing great feedback.
Please let me know if you have any other good ideas
