### ISSUE TITLE
v8.0.3 image is missing from quay.io

### ISSUE THREAD

**Issue by mikeage** [IBM/core-dump-handler#72]
Installing v8.0.3 gave me an ImagePullBackOff:

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m52s                  default-scheduler  Successfully assigned observe/core-dump-handler-rg9jv to ip-10-7-5-141.eu-west-1.compute.internal
  Normal   Pulling    2m25s (x4 over 3m51s)  kubelet            Pulling image "quay.io/icdh/core-dump-handler:v8.0.3"
  Warning  Failed     2m23s (x4 over 3m50s)  kubelet            Failed to pull image "quay.io/icdh/core-dump-handler:v8.0.3": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/icdh/core-dump-handler:v8.0.3 not found: manifest unknown: manifest unknown
  Warning  Failed     2m23s (x4 over 3m50s)  kubelet            Error: ErrImagePull
  Warning  Failed     116s (x6 over 3m49s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    102s (x7 over 3m49s)   kubelet            Back-off pulling image "quay.io/icdh/core-dump-handler:v8.0.3"
```

And indeed, the image isn't there; see https://quay.io/repository/icdh/core-dump-handler?tab=tags&tag=latest

Did something go wrong with the release process?

**Comment by No9** [comment]
Thanks for raising this.

Very strange. The build for a release tag is automated when the tag is generated by the release action during the chart update.
It looks like the tag event wasn't seen by quay.io as there is no build event for v8.0.3 and therefore no image.
I need to investigate further. 

I've create a tag for v8.0.3 based on the `main` image that was built using the same merge event for the release.
```
docker pull quay.io/icdh/core-dump-handler@sha256:1b78ec28bc990da8db74cbaf9a23cf4e07538763f3b89ad021e7e1ab0536a46d
docker tag quay.io/icdh/core-dump-handler@sha256:1b78ec28bc990da8db74cbaf9a23cf4e07538763f3b89ad021e7e1ab0536a46d quay.io/icdh/core-dump-handler:v8.0.3  
docker push quay.io/icdh/core-dump-handler:v8.0.3
```
Let us know how you get on.

**Comment by mikeage** [comment]
Thanks! I've upgraded my cluster to 8.0.3. It's running nicely.

**Comment by mikeage** [comment]
It looks like this may still be occurring in 8.2.0

**Comment by No9** [comment]
Fixed by generating the tag from main build again.
I'll raise this with quay.io

**Comment by No9** [comment]
Finally bottomed this out today. 
This is happening as I am cancelling older builds so that the latest builds get pushed through faster.
Cancelling a build seems to put the trigger into a disabled state. 
So when the build pipeline completes it's active build, usually the `main` branch it drops the `tag` build which is in the queue as the trigger is now disabled.
In the UI it looks like the tag build is queued but in reality it will be dropped when the trigger state is enforced hence the confusion.
