### ISSUE TITLE
Hardcoded AWS credentials

### ISSUE THREAD

**Issue by pkit** [IBM/core-dump-handler#75]
Why exactly this one insists on passing hardcoded clear text credentials for S3 access?
Here:
https://github.com/IBM/core-dump-handler/blob/5791642bad16030eb5a47c90c4f2b9281cd75548/core-dump-agent/src/main.rs#L365
`Credentials::new(None, None, None, None, None)` should be a valid option for using node-based credentials.

**Comment by No9** [comment]
Hey @pkit 
Insisting on credentials seemed like a reasonable default as core dumps can contain sensitive information and so the idea was to prevent any unintentional exposure.
I'm happy to revisit this as a configuration option if you have a valid use case. 
I'm also not 100% on what you mean by `node-based credentials` so would appreciate a pointer there.

**Comment by pkit** [comment]
@No9 the use case is pretty simple: EKS with AWS roles centrally managed by `eksctl` or any other gitops flow.
Now, to use `[core-dump-handler](https://github.com/IBM/core-dump-handler)` I need to set up secret in my gitops flow with clear text keys or invent some creative ways to hide it.
> prevent any unintentional exposure
I'm not sure how exactly a daemonset installation insisting on a clear-text keys improves any security...
> node-based credentials
AWS roles applied directly to EKS nodes

**Comment by No9** [comment]
@pkit Agree - putting clear text into your deployment pipeline is not optimal. 
The aim of insisting on credentials was to encourage users not to have open object storage endpoints.

In a gitops scenario others have used the following approach:
[Configure the chart to ignore secrets](https://github.com/IBM/core-dump-handler/blob/main/FAQ.md#how-do-i-apply-my-own-secrets) and used something like [vault](https://www.vaultproject.io/) or [external-secrets](https://github.com/external-secrets/external-secrets) to apply the secrets out of band from the deployment.

The upload is executed from a the pod rather than the node and I can't seem to find documentation around how authority is passed. Are you aware of docs and or projects where I can find out more info?

**Comment by pkit** [comment]
@No9 the role association works like this: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
ServiceAccount is associated with a particular AWS role that has S3 access.

**Comment by pkit** [comment]
Just FYI, I'm thinking about something like this:

```diff
diff --git a/core-dump-agent/src/main.rs b/core-dump-agent/src/main.rs
index 00e8ef2..9774326 100644
--- a/core-dump-agent/src/main.rs
+++ b/core-dump-agent/src/main.rs
@@ -359,17 +359,21 @@ fn get_bucket() -> Result<Bucket, anyhow::Error> {
         }
     };
 
+    let credentials = if s3_access_key.is_empty() || s3_secret.is_empty() {
+        Credentials::new(None, None, None, None, None)
+    } else {
+        Credentials::new(Some(s3_access_key.as_str()),
+                         Some(s3_secret.as_str()),
+                         None,
+                         None,
+                         None,
+        )
+    };
+
     let s3 = Storage {
         name: "aws".into(),
         region,
-        credentials: Credentials::new(
-            Some(s3_access_key.as_str()),
-            Some(s3_secret.as_str()),
-            None,
-            None,
-            None,
-        )
-        .unwrap(),
+        credentials: credentials.unwrap(),
         bucket: s3_bucket_name,
         location_supported: false,
     };
```
here credentials are used on a "best effort" basis, exactly like majority of AWS tools does it.

**Comment by pkit** [comment]
I've made these changes and also set the `secretRef` for keys to `optional`, and it worked quite fine.
But still the whole thing is kinda useless as it doesn't detect any segfaults...
Nothing is happens in the logs, even in `Debug` level.
Could it be that it cannot work across namespaces?

**Comment by No9** [comment]
The core config is done on the host so it covers all namespaces. 
Can you confirm the core pattern is getting set by logging into a host and running `sysctl kernel.core_pattern`
You should see something like 
`|/var/mnt/core-dump-handler/cdc -c=%c -e=%e -p=%p -s=%s -t=%t -d=/var/mnt/core-dump-handler/cores -h=%h -E=%E`

While on the host can you confirm the exe runs by executing `/var/mnt/core-dump-handler/cdc`
it should print out the options.

Also can you also confirm the version of EKS you are using? 

In the meantime I'll put your changes into a branch and have a look myself.

**Comment by pkit** [comment]
Yup, it seems like it sets the pattern allright.
Here's the log of one pod:
```
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:05Z INFO  core_dump_agent] no .env file found 
core-dump-handler-wq2lb coredump-container      That's ok if running in kubernetes
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:05Z INFO  core_dump_agent] Setting host location to: /var/mnt/core-dump-handler
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:05Z INFO  core_dump_agent] Current Directory for setup is /app
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:05Z INFO  core_dump_agent] Copying the crictl from ./crictl to /var/mnt/core-dump-handler/crictl
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Copying the composer from ./vendor/default/cdc to /var/mnt/core-dump-handler/cdc
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Starting sysctl for kernel.core_pattern /var/mnt/core-dump-handler/core_pattern.bak with |/var/mnt/core-dump-handler/cdc -c=%c -e=%e -p=%p -s=%s -t=%t -d=/var/mnt/core-dump-handler/cores -h=%h -E=%E
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Getting sysctl for kernel.core_pattern
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Created Backup of /var/mnt/core-dump-handler/core_pattern.bak
core-dump-handler-wq2lb coredump-container kernel.core_pattern = |/var/mnt/core-dump-handler/cdc -c=%c -e=%e -p=%p -s=%s -t=%t -d=/var/mnt/core-dump-handler/cores -h=%h -E=%E
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Starting sysctl for kernel.core_pipe_limit /var/mnt/core-dump-handler/core_pipe_limit.bak with 128
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Getting sysctl for kernel.core_pipe_limit
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Created Backup of /var/mnt/core-dump-handler/core_pipe_limit.bak
core-dump-handler-wq2lb coredump-container kernel.core_pipe_limit = 128
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Starting sysctl for fs.suid_dumpable /var/mnt/core-dump-handler/suid_dumpable.bak with 2
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Getting sysctl for fs.suid_dumpable
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Created Backup of /var/mnt/core-dump-handler/suid_dumpable.bak
core-dump-handler-wq2lb coredump-container fs.suid_dumpable = 2
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Creating /var/mnt/core-dump-handler/.env file with LOG_LEVEL=Debug
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Writing composer .env 
core-dump-handler-wq2lb coredump-container     LOG_LEVEL=Debug
core-dump-handler-wq2lb coredump-container     IGNORE_CRIO=false
core-dump-handler-wq2lb coredump-container     CRIO_IMAGE_CMD=img
core-dump-handler-wq2lb coredump-container     USE_CRIO_CONF=false
core-dump-handler-wq2lb coredump-container     FILENAME_TEMPLATE={uuid}-dump-{timestamp}-{hostname}-{exe_name}-{pid}-{signal}
core-dump-handler-wq2lb coredump-container     LOG_LENGTH=500
core-dump-handler-wq2lb coredump-container     
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:06Z INFO  core_dump_agent] Executing Agent with location : /var/mnt/core-dump-handler/cores
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:11Z INFO  core_dump_agent] Dir Content []
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:11Z INFO  core_dump_agent] INotify Starting...
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:11Z INFO  core_dump_agent] INotify Initialised...
core-dump-handler-wq2lb coredump-container [2022-03-12T13:16:11Z INFO  core_dump_agent] INotify watching : /var/mnt/core-dump-handler/cores
```
Unfortunately I don't have access to nodes in the current nodegroup (no ssh key was set up). I'm creating a debug-able nodegroup right now and will check out what's going on on these new hosts soon.

**Comment by No9** [comment]
The agent and install looks good.
Can you provide the EKS version when you have a minute?

**Comment by pkit** [comment]
> Can you provide the EKS version when you have a minute?

It's EKS 1.21 for control plane
Nodes have a mix of `v1.20.7-eks-135321` and `v1.21.2-eks-55daa9d`

**Comment by pkit** [comment]
Ok, found it:
```
$ /var/mnt/core-dump-handler/cdc
/var/mnt/core-dump-handler/cdc: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/mnt/core-dump-handler/cdc)
```
I have compiled it using the `Dockerfile` from the repo https://github.com/IBM/core-dump-handler/blob/main/Dockerfile

**Comment by No9** [comment]
OK is `ubi7` compatible?

**Comment by pkit** [comment]
Yup, it's `2.17`

**Comment by No9** [comment]
OK you should be able to use the rhel7 vendor option 
`--set daemonset.vendor=rhel7`
That uses cdc built with the `ubi7`
https://github.com/IBM/core-dump-handler/blob/main/Dockerfile#L1

**Comment by pkit** [comment]
Yup, found it. It works!
I think docs needs to be updated as the newest EKS version is `1.21` and it needs `vendor: rhel7` to work. :)

**Comment by pkit** [comment]
I can do PR with all the changes if it's ok

**Comment by No9** [comment]
Glad you've sorted it out and thanks for putting in the work - I'm sure it will be useful for others.
We should add it to the aws values file 
https://github.com/IBM/core-dump-handler/blob/main/charts/core-dump-handler/values.aws.yaml

Happy to take the PR and do a release. 
Can you also add a note to the chart README.md to outline all the options you needed to set to get this to work.
