### ISSUE TITLE
Core Dumping large memory applications

### ISSUE THREAD

**Issue by tjungblu** [IBM/core-dump-handler#81]
Hey @No9,

from #69 we had the customer requirements to configure limits - we came to the conclusion that there are indeed no limits on the OS side.

I tried to adapt the segfaulter script today with a bit more memory than necessary (6 gigs worth of 42s https://github.com/tjungblu/segfaulter) and run it as usual with

> kubectl run -i -t segfaulter --image=quay.io/tjungblu/segfaulter_6g --restart=Never

The core-dump triggered and albeit having only 4mb in size (which is fine, I guess 6gigs worth of 42s compress really well), I do have issues unzipping it:

```
Archive:  test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test.zip or
        test.zip.zip, and cannot find test.zip.ZIP, period.

```

Here is the zip in the pod:
```
[root@core-dump-handler-rq2ng cores]# ls -l
total 4076
-rw-r--r--. 1 root root 4173458 Mar 14 12:31 29a453fb-0c89-4d84-b618-6ad3523e74ee-dump-1647261075-segfaulter-segfaulter-1-4.zip

```

I assume we're running into issues with the limit of the original zip format, where this big of a dump would require a ZIP64: https://en.wikipedia.org/wiki/ZIP_(file_format)#ZIP64

There were no errors during collection, the upload didn't work as it wasn't configured, I pulled it via rsync:

```
[2022-03-14T12:30:03Z INFO  core_dump_agent] Executing Agent with location : /mnt/core-dump-handler/cores
[2022-03-14T12:30:03Z INFO  core_dump_agent] Dir Content []
[2022-03-14T12:30:03Z INFO  core_dump_agent] INotify Starting...
[2022-03-14T12:30:03Z INFO  core_dump_agent] INotify Initialised...
[2022-03-14T12:30:03Z INFO  core_dump_agent] INotify watching : /mnt/core-dump-handler/cores
[2022-03-14T12:31:28Z INFO  core_dump_agent] Uploading: /mnt/core-dump-handler/cores/29a453fb-0c89-4d84-b618-6ad3523e74ee-dump-1647261075-segfaulter-segfaulter-1-4.zip
[2022-03-14T12:31:28Z INFO  core_dump_agent] zip size is 4173458
[2022-03-14T12:31:28Z ERROR core_dump_agent] Upload Failed error sending request for url (https://xxx/XXX/29a453fb-0c89-4d84-b618-6ad3523e74ee-dump-1647261075-segfaulter-segfaulter-1-4.zip?uploads): error trying to connect: dns error: failed to lookup address information: Name or service not known
```

---
EDIT, actually looking into the composer log, there IS an error:
```
DEBUG - 2022-03-14T12:31:15.932866037+00:00 - Arguments: Args { inner: ["/mnt/core-dump-handler/cdc", "-c=18446744073709551615", "-e=segfaulter", "-p=1", "-s=4", "-t=1647261075", "-d=/mnt/core-dump-handler/cores", "-h=segfaulter", "-E=!usr!local!bin!segfaulter"] }
INFO - 2022-03-14T12:31:15.932992397+00:00 - Environment config:
 IGNORE_CRIO=false
CRIO_IMAGE_CMD=img
USE_CRIO_CONF=false
INFO - 2022-03-14T12:31:15.932997217+00:00 - Loading .env
INFO - 2022-03-14T12:31:15.933000150+00:00 - Set logfile to: "\"/var/mnt/core-dump-handler/composer.log\""
DEBUG - 2022-03-14T12:31:15.933019681+00:00 - Creating dump for 29a453fb-0c89-4d84-b618-6ad3523e74ee-dump-1647261075-segfaulter-segfaulter-1-4
DEBUG - 2022-03-14T12:31:15.933023182+00:00 - running ["pods", "--name", "segfaulter", "-o", "json"] "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/home/kubernetes/bin:/var/mnt/core-dump-handler"
DEBUG - 2022-03-14T12:31:16.126926097+00:00 - Create a JSON file to store the dump meta data
29a453fb-0c89-4d84-b618-6ad3523e74ee-dump-1647261075-segfaulter-segfaulter-1-4-dump-info.json
ERROR - 2022-03-14T12:31:28.576238180+00:00 - Error writing core file 
***Large file option has not been set***

```

Here's the file, if you want to look a bit into it: 
[test.zip](https://github.com/IBM/core-dump-handler/files/8244857/test.zip)

Any clue?

**Comment by No9** [comment]
Hey @tjungblu 
So the error is being thrown from the zip library here https://github.com/zip-rs/zip/blob/25a5b4e4ba6ebfb0adcbfbcd24a7947e909fcd9f/src/write.rs#L207 

There seems to be a large file option that can be set on the zip library 
https://github.com/zip-rs/zip/blob/25a5b4e4ba6ebfb0adcbfbcd24a7947e909fcd9f/src/write.rs#L132 

I'll take a look with your sample segfaulter

**Comment by No9** [comment]
Ok so the good news is that the large file option captures the core dump correctly but it causes the `iNotify` functionality to fail as the file is still reported as locked. 

I will look at it a little more but as noted in https://github.com/IBM/core-dump-handler/issues/29#issuecomment-952858532 I've had very mixed experience with iNotify in general and given we will need some sort of retry strategy for [cloud events](https://github.com/IBM/core-dump-handler/tree/cloud-event) it may be that we revert to scheduled only.

**Comment by tjungblu** [comment]
Thanks for the quick fix! Just verified your branch works.

**Comment by No9** [comment]
Hey @tjungblu 
I couldn't replicate the iNotify issue at all today so I have left the current agent config as is so we can release this without a major bump.
If it does crop up let me know otherwise I will come back around to it as part of the cloud events stuff.
