### ISSUE TITLE
Create demo video

### ISSUE THREAD

**Issue by No9** [IBM/core-dump-handler#9]
It would be great to get a demo of installing the tool and running the sample segfault app for people interested in using the project.
Link to the video should be available from the top of the project page.
This can be done on any hosting provider or a your own cluster some suggested steps are
1. show the configuration of the object store
1. Runs the helm chart with the params
1. Waits for the agent pod to be running 
1. Runs the sample test container 
    ```
    kubectl run -i -t segfaulter --image=quay.io/icdh/segfaulter --restart=Never
    ```
1. Downloads the generated zip file
1. Possibly show using gdb to get the stacktrace?

**Comment by adinhtdsibm** [comment]
@No9 As discussed, I can work on this issue. Please do assign my name and I will update you once I am done with the video.

**Comment by No9** [comment]
Closing as a presentation was done of these steps at the rust dublin meetup 
https://www.youtube.com/watch?v=gdafrv1ZR5Q
